server {
    listen 80;
    listen 13130;
    server_name mrvn.site www.mrvn.site;
    root /usr/share/nginx/sites/root;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 13131;
    server_name claw.mrvn.site;
    root /usr/share/nginx/sites/claw;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 13132;
    server_name ds.mrvn.site;
    root /usr/share/nginx/sites/ds;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 13133;
    server_name help.mrvn.site;
    root /usr/share/nginx/sites/help;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 13134;
    server_name who.mrvn.site;
    root /usr/share/nginx/sites/who;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 13135;
    server_name what.mrvn.site;
    root /usr/share/nginx/sites/what;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 13136;
    server_name how.mrvn.site;
    root /usr/share/nginx/sites/how;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 13137;
    server_name when.mrvn.site;
    root /usr/share/nginx/sites/when;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 13138;
    server_name why.mrvn.site;
    root /usr/share/nginx/sites/why;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 13139;
    server_name ai.mrvn.site;
    root /usr/share/nginx/sites/ai;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 13140;
    server_name zww.mrvn.site;
    root /usr/share/nginx/sites/zww;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
