server {
    listen 80;
    server_name mrvn.site www.mrvn.site;
    root /usr/share/nginx/sites/root;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 80;
    server_name what.mrvn.site;
    root /usr/share/nginx/sites/what;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 80;
    server_name zww.mrvn.site;
    root /usr/share/nginx/sites/zww;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
